config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  get '/classrooms/filtered_index' => 'classrooms#filtered_index'
  get '/classrooms/filtered_index_classroom' => 'classrooms#filtered_index_classroom'
  get '/teachers/filtered_index' => 'teachers#filtered_index'
  get '/teachers/filtered_index_teacher' => 'teachers#filtered_index_teacher' 
  get '/students/filtered_index' => 'students#filtered_index'

  resources :schools , :classrooms, :teachers, :students, :subjects

  
  

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
	belongs_to :school
	has_and_belongs_to_many :teachers
	has_many :students
	has_and_belongs_to_many :subjects

	validates :name, :number_of_students, presence: true
	validates :name, uniqueness: true

	def school_details
		self.school
	end
	def subject_details
		self.subjects
	end
	
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
	def index
		@classrooms=Classroom.all
		respond_to do |format|
 			format.json { render :json => @classrooms, :status => :ok }
		end
	end
	def show
	 begin
		@classroom = Classroom.find(params[:id])
		respond_to do |format|
 			format.json { render :json => @classroom, :status => :ok }
 		end
		rescue => e
			p e.message
			respond_to do |format|
 				format.json {render :json =>  { "error" => e.message}, :status  => :unprocessable_entity}
 			end
	  end
	end
	def create
		begin
		 @classroom = Classroom.new(params.require(:classroom).permit(:name, :number_of_students, :school_id).merge(:subject_ids=>params[:classroom][:subject_ids]))
		 if @classroom.save!
		 	respond_to do |format|
 			format.json {render json: @classroom, :status => :ok}
 			end
 		end
		rescue => e
    	respond_to do |format|
 			format.json {render :json => { "error" => e.message}, :status  => :unprocessable_entity}
 		end
     end
	end
	def update
		begin
		@classroom = Classroom.find(params[:id])
		if @classroom.update_attributes!(params.require(:classroom).permit(:name, 
			:number_of_students, :school_id).merge(:subject_ids=>params[:classroom][:subject_ids]))
			respond_to do |format|
 			format.json {render :json => @classroom, :status => :ok}
 			end
 		end
		rescue => e
	    	p e.message
			respond_to do |format|
 				format.json {render :json => {"error" => e.message}, :status  => :unprocessable_entity}
 			end
		end
	end
	def destroy
	    begin
		@classroom = Classroom.find(params[:id])
	   	if @classroom.destroy
	   	  @classrooms = Classroom.all
	      respond_to do |format|
 		  format.json {render :json => @classroom, :status => :ok}
 		  end
	    end
	    rescue => e
	   	  p e.message
       	  respond_to do |format|
 		  format.json {render :json => {"error" => e.message}, :status  => :unprocessable_entity}
 		  end
    	end
	end
  def filtered_index
    # refactor this to generate dynamic query
    begin
      @school = School.find(params[:school_id])
	    @classrooms = Classroom.where(:school_id => @school.id)
      render :json => @classrooms.to_json(:methods => [:classroom, :subject_details, :school_details]), :status => :ok
			rescue => e
			p e.message
			respond_to do |format|
 			format.json {render :json =>  { "error" => e.message}, :status  => :unprocessable_entity}
 			end
  	end
  end
  def filtered_index_classroom
    # refactor this to generate dynamic query
    begin
    	if params[:classroom_id] 
	    	p Classroom.where(:id => params[:classroom_id])
	      @classroom = Classroom.where(:id => params[:classroom_id]).all
	    	render :json => @classroom.to_json(:methods => [:classroom, :subject_details, :school_details]), :status => :ok
	    else
	    	format.json {render :json =>  "error", :status  => :unprocessable_entity}
	    end	
			rescue => e
			p e.message
			respond_to do |format|
			format.json {render :json =>  { "error" => e.message}, :status  => :unprocessable_entity}
 			end
	  end
  end
end

app/helpers/classroom_helper.rb
module ClassroomHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/views/classrooms/_classroom.html.erb
<div id="createClassroomContainer" class="hidden" align="center">
	<form action=""  id="createClassForm" method="" class="form-horizontal">
	
	  <div class="container">
      <div class="row" >
        <div class="col-md-3">
        </div>
        <div class="col-md-6">
          <div ><h3>Create Classroom</h3></div>
          
          <div class="form-group">
            <div class="col-sm-4">
              <label>School Name :</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="schoolName" disabled>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-4">
              <label>Classroom Name :</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="classroomName" name="classroom_name">
            </div>
          </div>
          <div class="form-group">
          <div class="col-sm-4">
            <label>Number Of Students :</label>
          </div>
          <div class="col-sm-4">
            <input type="text" id="numberOfStudent" name="no_of_student">
          </div>
          </div>
          <div class="form-group">
            <div class="col-sm-4"> 
              <label>Subject :</label>
            </div>
            <div class="col-sm-4">
              <select id="ddSubject" multiple="true" size="3" width="10px" name="classroom_subject">
              </select>
              <input type="hidden" id="classHidden">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-4">
              <button type="button" id="btnCreateClass" class="btn btn-primary">Submit</button>
            </div>
            <div class="col-sm-4">
              <button type="button" id="cancel" class="btn btn-warning">Cancel</button>
            </div>
          </div>
        </div>
        <div class="col-md-3">
        </div>
        </div>
     </div>
     </div>
	</form>
</div>
<div id="allClassroom" class="hidden" align="center">
    <h3>Classroom List</h3>
    <a id="createClassroom" class="btn btn-success">Add New Classroom</a></br>
   <input type="hidden" id="classHidden"></br>
   <input type="hidden" id="classHiddenSchool">
    <table border="1" id="tableClassroom" width="70%" class="table table-bordered">
    <thead>
      <tr>
        <!-- <th>
          School Name
        </th> -->
        <th>
          Classroom Name
        </th>
        <th>
           Number Of Students
        </th>
        <th>
           Subject
        </th>
         <th colspan="6" align="center">
          Actions
        </th>
      </tr>
    </thead>
    <tbody>
    </tbody>
    </table>
    <button id="home" type="button" class="btn btn-warning">Home</button>
    <button id="back" type="button" class="btn btn-default">Back</button>
</div>
 <div id="editClassroomContainer" class="hidden" align="center">
  <form action=""  id="editClassForm" method="" class="form-horizontal">
    <div class="container">
      <div class="row" >
        <div class="col-md-3">
        </div>
        <div class="col-md-6">
          <div ><h3>Edit Classroom</h3></div>

          <div class="form-group">
            <div class="col-sm-4">
              <label>School Name :</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="schoolName" disabled>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-4">
              <label>Classroom Name :</label>
            </div>
            <div class="col-sm-4">
             <input type="text" id="classroomName" name="classroom_name">
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-4">
              <label>Number Of Students :</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="numberOfStudent" name="no_of_student">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-4"> 
              <label>Subject :</label>
            </div>
            <div class="col-sm-4">
             <select id="ddSubject" multiple="true" size="3" width="10px" name="classroom_subject">
            </select>
            <input type="hidden" id="classHidden">
            </div>
          </div>
           <div class="form-group">
            <div class="col-sm-4">
            <button type="button" id="btnEditClass" class="btn btn-primary">Update</button>
            </div>
            <div class="col-sm-4">
            <button type="button" id="cancel" class="btn btn-warning">Cancel</button>
            </div>
          </div>

        </div>
        <div class="col-md-3">
        </div>
        </div>
     </div>
     </div>
  </form>
</div>

app/views/classrooms/_form.html.erb
<%= form_for @classroom do |f| %>
 
  <% if @classroom.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@classroom.errors.count, "error") %> prohibited
        this classroom from being saved:
      </h2>
      <ul>
        <% @classroom.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <p>
    <%= f.label :school_id %><br>
    <%= select_tag 'classroom[school_id]', options_from_collection_for_select(School.all, :id, :name) %>
 </p>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :no_of_students %><br>
    <%= f.text_area :number_of_students %>
  </p>
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/classrooms/edit.html.erb
<h3>Edit Classroom Details</h1>

	<%= form_for :classroom, url: classroom_path(@classroom.id) , method: :patch do |f| %>
	
		<%if @classroom.errors.any?  %>
			<div id="error_explain">
				<h2>
					<%= pluralize(@classroom.errors.count, "error")%> Prohibited this classroom from being edited
				</h2>
				<ul>
					<%= @classroom.errors.full_message.each do |msg| %>
						<li>
							<%= msg %>
						</li>
					<%end%>	
				</ul>
			</div>
		<% end %>

		<body>
		 <table border="0" cellpadding="0" cellspacing="0" width="60%">
			<tr>
	          <td>
	            <%= f.label :school_id %><br>
	          </td>
	          <td>
	             <%= @classroom.school.name%>
	          </td>
	      	</tr>
	      	<tr>
	          <td width="120px">
	  			     <%= f.label :name %>
	  		  </td>
	  		  <td width="120px">
	      		  <%= f.text_field :name %>
	    		</td>
	 	    </tr>
	   	 	<tr>
	      		<td width="120px">
	      		<%= f.label :number_of_students %>
	      		</td>
	      		<td width="120px">
	      		<%= f.number_field :number_of_students %>
	      	</td>
	    	</tr>
	 	
		 	<tr>
		 		<td align="center">
					<%= f.submit%>
				</td>
			</tr>
			<tr >
		 		<td align="center">
					<%= link_to 'Back', classrooms_path%>
				</td>
			</tr>
		</body>
		<% end %>
		

app/views/classrooms/index.html.erb
<h3>Listing Classrooms</h3>
<%= link_to 'Add New Classroom', new_classroom_path %></br></br>
<table border="2">
	<tr>
		<th>
			Classroom Name
		</th>
		<th>
			 Number Of Students
		</th>
		<th>
			School
		</th>
		<th colspan="6">
			Actions
		</th>
	</tr>
	<% @classrooms.each do |classroom|%>
		<tr>
			<td>
				<%= classroom.name%>
			</td>
			<td>
				<%= classroom.number_of_students%>
			</td>
			<td>
				<%= classroom.school.name%>
			</td>
			<td colspan="2">
				<%= link_to 'Show', classroom_path(classroom) %>
			</td>
			
			<td colspan="2">
				<%= link_to 'Edit', edit_classroom_path(classroom) %>
			</td>
			<td colspan="2">
				<%= link_to 'Destroy', classroom_path(classroom), method: :delete, data: { confirm: 'Do you want to destroy this record?' } %>
			</td>
		</tr>

	<%end%>

</table>
<%= link_to 'Back', schools_path %></br></br>

app/views/classrooms/new.html.erb
<!-- <h1>New Classroom</h1> -->
<%= form_for :classroom, url: classrooms_path do |f| %>
	<% if @classroom.errors.any? %>
		<div id="error explaination">
			<h2>
				<%= pluralize(@classroom.errors.count,"error") %> Prohibited this classroom from being saved:
			</h2>
			<ul>
				<% @classroom.errors.full_messages.each do|msg|%>
				<li>
					<%= msg%>
				</li>
				<%end%>
			</ul>
		</div>
	<%end%>
	<div align="center" width="40%">
		<strong>Add New Classroom</strong>
	</div>
	<body>
	 <table border="0" cellpadding="0" cellspacing="0" width="60%">
      <tr>
          <td>
            <%= f.label :school_id %><br>
          </td>
          <td>
             <%= select_tag 'classroom[school_id]', options_from_collection_for_select(School.all, :id, :name) %>
          </td>
      </tr>
      <tr>
          <td width="120px">
  			     <%= f.label :name %>
  		  </td>
  		  <td width="120px">
      		  <%= f.text_field :name %>
    		</td>
 	    </tr>
   	 <tr>
      	<td width="120px">
      		<%= f.label :number_of_students %>
      	</td>
      	<td width="120px">
      		<%= f.number_field :number_of_students %>
      	</td>
    	</tr>
    	
   	<tr>
   		<td align="center">
  			<%= f.submit%>
  		</td>
  	</tr>
  	<tr >
   		<td align="center">
  			<%= link_to 'Back', classrooms_path%>
  		</td>
  	</tr>
	</body>
 <% end -%>

app/views/classrooms/show.html.erb
<div align="center" width="">
		<strong>View Classroom Details</strong>
</div>
<table border="2">
	<tr>
		<td>
			<strong>Classroom Name</strong>
		</td>
		<td>
			<strong>Number Of Students</strong>
		</td>
		<td align="center">
			<strong>School</strong>
		</td>
		
	</tr>
	<tr>
		<td>
			<%= @classroom.name %>
		</td>
		<td>
			<%= @classroom.number_of_students %>
		</td>
		<td>
			<%= @classroom.school.name %>
		</td>
		
	</tr>

</table>
<%= link_to 'Edit', edit_classroom_path(@classroom) %> |
<%= link_to 'Back', classrooms_path%>