config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  get '/classrooms/filtered_index' => 'classrooms#filtered_index'
  get '/classrooms/filtered_index_classroom' => 'classrooms#filtered_index_classroom'
  get '/teachers/filtered_index' => 'teachers#filtered_index'
  get '/teachers/filtered_index_teacher' => 'teachers#filtered_index_teacher' 
  get '/students/filtered_index' => 'students#filtered_index'

  resources :schools , :classrooms, :teachers, :students, :subjects

  
  

end

app/models/student.rb
class Student < ActiveRecord::Base
	belongs_to :school
	belongs_to :classroom
	has_and_belongs_to_many :teachers
	has_and_belongs_to_many :subjects

	validates :name, :father_name, :mother_name, :phone_no, :address, :city, :zipcode, :state, presence: true
	validates :name, uniqueness: true
	validates :phone_no, length: {minimum:10,maximum:10}
	
	def school_details
		self.school
	end

	def classroom_details
		self.classroom
	end
	
	def subject_details
		self.subjects
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def index
		@students=Student.all
		respond_to do |format|
 			# format.html 
 			format.json { render :json => @students, :stauts => :ok}
 		end
	end
	def show
		begin
			@student=Student.find(params[:id])
			respond_to do |format|
 			format.json { render :json => @student, :stauts => :ok}
 			end
 			rescue => e
		 	p e.message
		 	respond_to do |format|
 			format.json { render :json => { "error" => e.message}, :status => :unprocessable_entity}
 			end
		end
	end
	def create
		begin
		@student = Student.new(student_param)
		if @student.save!
			respond_to do |format|
 			format.json {render :json => @student, :status  => :ok}
 			end
 		end
		rescue => e
			respond_to do |format|
 			format.json { render :json => { "error" => e.message}, :status => :unprocessable_entity}
 			end
		end
	end
	def update
		begin
			p "parama"
			p params
			p "parama"
		@student=Student.find(params[:id])
		p @student
		if @student.update_attributes!(student_param)
			p @student
			respond_to do |format|
				format.json {render :json => @student, :status => :ok}
 			end
 		end
		rescue => e
			p e.message
			respond_to do |format|
 				format.json {render :json => {"error" => e.message}, :status => :unprocessable_entity}
 			end
		end
	end
	def destroy
		p params[:id]
		begin
			@student=Student.find(params[:id])
			if @student.destroy
				@students = Student.all
				respond_to do |format|
 				format.json {render :json => @student, :status => :ok}
 			end
			end
			rescue => e
			p e.message
			respond_to do |format|
 			format.json {render :json => {"error" => e.message}, :status => :unprocessable_entity}
 			end
		end
	end
	def filtered_index
    # refactor this to generate dynamic query
    begin
      @classroom = Classroom.find(params[:classroom_id])
	  @students = Student.where(:classroom_id => @classroom.id)
      # @students = Student.where(:classroom_id => params[:classroom_id])
      render :json => @students.to_json(:methods => [:classroom, :subject_details, :school_details]), :status => :ok
		rescue => e
		p e.message
		respond_to do |format|
 		format.json {render :json =>  { "error" => e.message}, :status  => :unprocessable_entity}
 		end
	  end
  end
	private
	def student_param
		 params.require(:student).permit(:name, :father_name, :mother_name, :phone_no, :address, :city, :zipcode, :state, :school_id, :classroom_id)
	end	
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
 
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@student.errors.count, "error") %> prohibited
        this student from being saved:
      </h2>
      <ul>
        <% @student.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <p>
    <%= f.label :school_id %><br>
    <%= select_tag 'student[school_id]', options_from_collection_for_select(School.all, :id, :name) %>
 </p>
 <p>
    <%= f.label :classroom_id %><br>
    <%= select_tag 'student[classroom_id]', options_from_collection_for_select(Classroom.all, :id, :name) %>
 </p>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :father_name %><br>
    <%= f.text_field :father_name %>
  </p>
  <p>
    <%= f.label :mother_name %><br>
    <%= f.text_field :mother_name %>
  </p>
  
  <p>
    <%= f.label :phone_no%><br>
    <%= f.text_field :phone_no%>
  </p>
  <p>
    <%= f.label :address%><br>
    <%= f.text_area :address%>
  </p>
 <p>
    <%= f.label :city%><br>
    <%= f.text_field :city%>
 </p>
  <p>
    <%= f.label :zipcode%><br>
    <%= f.text_field :zipcode%>
 </p>
  <p>
    <%= f.label :state%><br>
    <%= f.text_field :state%>
 </p>
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/students/_student.html.erb
<div id="allStudent" class="hidden" align="center">
    <h3>Student List</h3>
    <a class="btn btn-success" id="createStudent">Add New Student</a></br>
   <input type="hidden" id="hdnClassId"></br>
   <input type="hidden" id="hdnClassName">
   <input type="hidden" id="hdnSchoolName">
   <input type="hidden" id="hdnSchoolId">
    <table border="1" id="tableStudent" width="70%" class="table table-bordered">
    <thead>
      <tr>
        <th>
           Student Name
        </th>
        <th>
          School Name
        </th>
        <th>
          Classroom Name
        </th>
        <th>
            Father Name
        </th>
        <th>
          Mother Name
        </th>
        <th>
           Phone No
        </th>
        <th>
          Address
        </th>
        <th>
          City
        </th>
        <th>  
          Zipcode
        </th>
        <th>
          State
        </th>
         <th colspan="6">
          Actions
        </th> 
        
      </tr>
    </thead>
    <tbody>
    </tbody>
    </table>
    <button id="home" type="button" class="btn btn-warning">Home</button>
    <button id="back" type="button" class="btn btn-default">Back</button>
</div>
<div id="createStudentContainer" class="hidden">
<form action=""  id="createStudentForm" method="" class="form-horizontal">
    <div class="container">
      <div class="row" >
        <div class="col-md-3">
        </div>
        <div class="col-md-6">
          <div align="center"><h3>Create Student</h3></div>

          <div class="form-group">
            <div class="col-sm-4">
              <label>School Name :</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="schoolName" disabled>
            </div>
          </div>  
          <div class="form-group">
            <div class="col-sm-4">
              <label>Classroom Name :</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="classroomName" disabled>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-4">
              <label>Student Name :</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="studentName" name="student_name">
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-4">
              <label>Father Name :</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="fatherName" name="father_name">
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-4">
              <label>Mother Name :</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="motherName" name="mother_name">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-4">
              <label>Phone No :</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="phoneNo" name="student_phone">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-4">
              <label>Address:</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="address" name="student_address">
            </div>
          </div>
          <div class="form-group">
         
            <div class="col-sm-4">
              <label>City:</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="city" name="student_city">
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-4">
              <label>Zipcode:</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="zipcode" name="student_zipcode">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-4">
              <label>State:</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="state" >
              <input type="hidden" id="hdnSchoolId">
              <input type="hidden" id="hdnSchoolName">
              <input type="hidden" id="hdnClassName">
              <input type="hidden" id="hdnClassId">
          </div>
          </div>
          <div class="form-group">
            <div class="col-sm-4">
              <button type="button" id="btnCreateStudent" class="btn btn-primary">Submit</button>
            </div>
            <div class="col-sm-4">
              <button id="cancel" type="button" class="btn btn-warning">Cancel</button>
            </div>
          </div>

        </div>
        <div class="col-md-3">
        </div>
        </div>
     </div>
     </div>
  </form>
</div>
<div id="editStudentContainer" class="hidden">
<form action=""  id="editStudentForm" method="" class="form-horizontal">
  
    <div class="container">
      <div class="row" >
        <div class="col-md-3">
        </div>
        <div class="col-md-6">
          <div align="center"><h3>Edit Student Details</h3></div>
          <div class="form-group">
            <div class="col-sm-4">
              <label>School Name :</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="schoolName" disabled>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-4">
              <label>Classroom Name :</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="classroomName" disabled>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-4">
              <label>Student Name :</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="studentName" name="student_name">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-4">
              <label>Father Name :</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="fatherName" name="father_name">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-4">
              <label>Mother Name :</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="motherName" name="mother_name">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-4">
              <label>Phone No :</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="phoneNo" name="student_phone">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-4">
              <label>Address:</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="address" name="student_address">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-4">
              <label>City:</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="city" name="student_city">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-4">
              <label>Zipcode:</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="zipcode" name="student_zipcode">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-4">
              <label>State:</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="state" >
              <input type="hidden" id="hdnSchoolId">
              <input type="hidden" id="hdnSchoolName">
              <input type="hidden" id="hdnClassName">
              <input type="hidden" id="hdnClassId">

            </div>
          </div>
           <div class="form-group"> 
            <div class="col-sm-4">
            <button type="button" id="btnEditStudent" class="btn btn-primary">Update</button>
            </div>
            <div class="col-sm-4">
            <button id="cancel" type="button" class="btn btn-warning">Cancel</button>
            </div>
          </div>
        </div>
        <div class="col-md-3">
        </div>
        </div>
     </div>
     </div>
  </form>
</div>

app/views/students/edit.html.erb
<h3>Edit Student Details</h1>

	<%= form_for :student, url: student_path(@student.id) , method: :patch do |f| %>
	
		<%if @student.errors.any?  %>
			<div id="error_explain">
				<h2>
					<%= pluralize(@student.errors.count, "error")%> Prohibited this student from being edited
				</h2>
				<ul>
					<%= @student.errors.full_message.each do |msg| %>
						<li>
							<%= msg %>
						</li>
					<%end%>	
				</ul>
			</div>
		<% end %>

		<body>
		  <table border="0" cellpadding="0" cellspacing="0" width="60%">
	          <tr>
	            <td>
	              <%= f.label :school_id %>
	            </td>
	            <td>
	               <%= @student.school.name%>
	            </td>
	          </tr>
	          <tr>
	            <td>
	              <%= f.label :classroom_id%>
	            </td>
	            <td>
	              <%= @student.classroom.name%>
	               
	            </td>
	          </tr>
	          <tr>
	            <td width="120px">
	               <%= f.label :name %>
	          </td>
	          <td width="120px">
	              <%= f.text_field :name %>
	          </td>
	        </tr>
	         <tr>
	            <td width="120px">
	               <%= f.label :father_name %>
	          </td>
	          <td width="120px">
	              <%= f.text_field :father_name %>
	          </td>
	        </tr>
	         <tr>
	            <td width="120px">
	               <%= f.label :mother_name %>
	          </td>
	          <td width="120px">
	              <%= f.text_field :mother_name %>
	          </td>
	        </tr>
	      <tr>
	        <td width="120px">
	           <%= f.label :phone_no%>
	        </td>
	        <td>
	          <%= f.text_field :phone_no ,:maxlength => 10,:size => 20 %>
	        </td>
	      </tr>
	      <tr>
	        <td width="120px">
	           <%= f.label :address%>
	        </td>
	        <td>
	          <%= f.text_area :address  %>
	        </td>
	      </tr>
	       <tr>
	            <td width="120px">
	               <%= f.label :city %>
	          </td>
	          <td width="120px">
	              <%= f.text_field :city %>
	          </td>
	        </tr>
	         <tr>
	            <td width="120px">
	               <%= f.label :zipcode %>
	          </td>
	          <td width="120px">
	              <%= f.text_field :zipcode %>
	          </td>
	        </tr>
	       <tr>
	            <td width="120px">
	               <%= f.label :state %>
	          </td>
	          <td width="120px">
	              <%= f.text_field :state %>
	          </td>
	        </tr>
			<tr>
			  <td align="center">
				  <%= f.submit%>
	   		  </td>
			</tr>
			<tr>
			  <td align="center">
				  <%= link_to 'Back', students_path%>
			  </td>
			</tr>
		</body>
<% end %>
		

app/views/students/index.html.erb
<h3>Listing Students</h1>
<%= link_to 'Add New Student', new_student_path %></h3></br></br>
<table border="1">
	<tr>
		<th>
			Student Name
		</th>
		<th>
			 Father Name
		</th>
		<th>
			Mother Name
		</th>
		<th>
			Phone Number
		</th>
		<th>
			Address
		</th>
		<th>
			City
		</th>
		<th>
			Zipcode
		</th>
		<th>
			State
		</th>
		<th>	
			School
		</th>
		<th>
			Classroom
		</th>
		<th colspan="6">
			Actions
		</th>
	</tr>
	<% @students.each do |student|%>
		<tr>
			<td>
				<%= student.name%>
			</td>
			<td>
				<%= student.father_name%>
			</td>
			<td>
				<%= student.mother_name%>
			</td>
			<td>
				<%= student.phone_no%>
			</td>
			<td>
				<%= student.address%>
			</td>
			<td>
				<%= student.city%>
			</td>
			<td>
				<%= student.zipcode%>
			</td>
			<td>
				<%= student.state%>
			</td>
			
			<td>
				<%= student.school.name%>
			</td>
			<td>
				<%= student.classroom.name%>
			</td>
			<td colspan="2">
				<%= link_to 'Show', student_path(student) %>
			</td>
			<td colspan="2">
				<%= link_to 'Edit', edit_student_path(student) %>
			</td>
			<td colspan="2">
				<%= link_to 'Destroy', student_path(student), method: :delete, data: { confirm: 'Do you want to destroy this record?' } %>
			</td>
		</tr>

	<%end%>

</table>
<%= link_to 'Back', schools_path %></br></br>

app/views/students/new.html.erb
<!-- <h1>New Classroom</h1> -->
<%= form_for :student, url: students_path do |f| %>
	<% if @student.errors.any? %>
		<div id="error explaination">
			<h2>
				<%= pluralize(@student.errors.count,"error") %> Prohibited this student from being saved:
			</h2>
			<ul>
				<% @student.errors.full_messages.each do|msg|%>
				<li>
					<%= msg%>
				</li>
				<%end%>
			</ul>
		</div>
	<%end%>
	<div align="center" width="40%">
		<strong>Add New Student</strong>
	</div>
	<body>
	     <table border="0" cellpadding="0" cellspacing="0" width="60%">
          <tr>
            <td>
              <%= f.label :school_id %>
            </td>
            <td>
               <%= select_tag 'student[school_id]', options_from_collection_for_select(School.all, :id, :name) %>
            </td>
          </tr>
          <tr>
            <td>
              <%= f.label :classroom_id%>
            </td>
            <td>
              <%= select_tag 'student[classroom_id]', options_from_collection_for_select(Classroom.all, :id, :name) %>
               
            </td>
          </tr>
          <tr>
            <td width="120px">
               <%= f.label :name %>
            </td>
            <td width="120px">
              <%= f.text_field :name %>
            </td>
          </tr>
          <tr>
            <td width="120px">
               <%= f.label :father_name %>
            </td>
            <td width="120px">
               <%= f.text_field :father_name %>
            </td>
          </tr>
          <tr>
             <td width="120px">
                 <%= f.label :mother_name %>
             </td>
             <td width="120px">
                <%= f.text_field :mother_name %>
             </td>
          </tr>
          <tr>
             <td width="120px">
               <%= f.label :phone_no%>
             </td>
             <td>
               <%= f.text_field :phone_no ,:maxlength => 10,:size => 20 %>
             </td>
          </tr>
          <tr>
             <td width="120px">
               <%= f.label :address%>
             </td>
             <td>
               <%= f.text_area :address  %>
             </td>
          </tr>
           <tr>
                <td width="120px">
                   <%= f.label :city %>
              </td>
              <td width="120px">
                  <%= f.text_field :city %>
              </td>
            </tr>
             <tr>
                <td width="120px">
                   <%= f.label :zipcode %>
              </td>
              <td width="120px">
                  <%= f.text_field :zipcode %>
              </td>
            </tr>
           <tr>
                <td width="120px">
                   <%= f.label :state %>
              </td>
              <td width="120px">
                  <%= f.text_field :state %>
              </td>
            </tr>
       	   <tr>
       		    <td align="center">
      			      <%= f.submit%>
      		   </td>
      	   </tr>
      	   <tr>
       		    <td align="center">
      			      <%= link_to 'Back', students_path%>
      		    </td>
      	   </tr>
	</body>
 <% end -%>

app/views/students/show.html.erb
<div align="center" width="">
		<strong>View Student Details</strong>
</div>
<table border="1">
	<tr >
		<td>
			<strong>Student Name</strong>
		</td>
		<td>
			<strong>Father Name</strong>
		</td>
		<td>
			<strong>Mother Name</strong>
		</td>
		<td>
			<strong>Phone No.</strong>
		</td>
		<td>
			<strong>Address</strong>
		</td>
		<td>
			<strong>City</strong>
		</td>
		<td>
			<strong>Zipcode</strong>
		</td>
		<td>
			<strong>State</strong>
		</td>
		<td align="center">
			<strong>School</strong>
		</td>
		<td align="center">
			<strong>Classroom</strong>
		</td>
	</tr>
	<tr>
		<td>
			<%= @student.name %>
		</td>
		<td>
			<%= @student.father_name %>
		</td>
		<td>
			<%= @student.mother_name%>
		</td>
		<td>
			<%= @student.phone_no%>
		</td>
		<td>
			<%= @student.address%>
		</td>
		<td>
			<%= @student.city%>
		</td>
		<td>
			<%= @student.zipcode%>
		</td>
		<td>
			<%= @student.state%>
		</td>
		<td>
			<%= @student.school.name%>
		</td>
		<td>
			<%= @student.classroom.name%>
		</td>
	</tr>

</table>
<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path%>