config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  get '/classrooms/filtered_index' => 'classrooms#filtered_index'
  get '/classrooms/filtered_index_classroom' => 'classrooms#filtered_index_classroom'
  get '/teachers/filtered_index' => 'teachers#filtered_index'
  get '/teachers/filtered_index_teacher' => 'teachers#filtered_index_teacher' 
  get '/students/filtered_index' => 'students#filtered_index'

  resources :schools , :classrooms, :teachers, :students, :subjects

  
  

end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_and_belongs_to_many :schools
	has_and_belongs_to_many :teachers
	has_and_belongs_to_many :classrooms
	has_and_belongs_to_many :students

	validates :name, presence: true
	validates :name, uniqueness: true
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
	def index
		@subjects=Subject.all
		respond_to do |format|
 		format.json { render :json => @subjects, :status => :ok}
		end
	end
	def show
		begin
		@subject=Subject.find(params[:id])
		respond_to do |format|
 		format.json { render :json => @subject, :status => :ok}
		end
		rescue => e
			p e.message
			respond_to do |format|
 			format.json { render :json => { "error" => e.message}, :status => :unprocessable_entity}
			end
		end
	end
	def create
		begin
		@subject=Subject.new(subject_param)
		if @subject.save!
			respond_to do |format|
 			format.json {render :json => @subject, :status  => :ok}
 			end
 		end
		rescue => e
			p e.message
			respond_to do |format|
 			format.json {render :json => {"error" => e.message}, :status =>:unprocessable_entity}
 			end
		end
	end
	def update
		begin
		@subject=Subject.find(params[:id])
		if @subject.update_attributes!(subject_param)
			respond_to do |format|
				# format.html {render 'show'}
 				format.json {render :json => @subject, :status => :ok}
 			end
		end
		rescue => e
			p e.message
			respond_to do |format|
 			format.json {render :json => {"error" => e.message}, :status =>:unprocessable_entity}
 			end
		end
	end
	def destroy
		begin
		@subject=Subject.find(params[:id])
		if @subject.destroy
			@subjects = Subject.all
			respond_to do |format|
 			format.json {render :json => @subject, :status => :ok}
 			end
		end
		rescue => e
			p e.message
			respond_to do |format|
			@subjects = Subject.all
 			format.json {render :json => {"error" => e.message}, :status => :unprocessable_entity}
 			end
		end
	end
	private 
	def subject_param
		params.require(:subject).permit(:name)
	end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_for @subject do |f| %>
 
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@subject.errors.count, "error") %> prohibited
        this subject from being saved:
      </h2>
      <ul>
        <% @subject.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/subjects/_index.html.erb
<div id="subjectContainer" class="hidden" align="center">
	<form action="" method="" id="addSubjectForm">
		<h3>Add Subject</h3>
		<div>
			<input type="text" id="subjectName"  placeholder="Subject Name" name="subject_name">
		</div>
		<div>
		</div>
        <div> 
        	<button type="button" id="submitSubject" class="btn btn-primary">Save Subject</button>
        	<button type="button" id="cancel" class="btn btn-warning" >Cancel</button>
        </div>
	</form>
</div>
<div id="allSubjectContainer" class="hidden" align="center">
		<h3>Subject List</h3>
		<a id="createSubject">Add Subject</a>
		<table border="1" id="tableSubject" width="40%" class="table table-bordered">
		<thead>
			<tr>
				 <th>
					Subject Name
				 </th>
				 <th colspan="6">
					Actions
				 </th> 
			</tr>
		</thead>
		<tbody>
		</tbody>
		</table>
		<button type="button" id="home" class="btn btn-warning">Home</button>
	</form>
</div>

app/views/subjects/edit.html.erb
<h3>Edit Subject Details</h1>

	<%= form_for :subject, url: subject_path(@subject.id) , method: :patch do |f| %>
	
		<%if @subject.errors.any?  %>
			<div id="error_explain">
				<h2>
					<%= pluralize(@subject.errors.count, "error")%> Prohibited this subject from being edited
				</h2>
				<ul>
					<%= @subject.errors.full_message.each do |msg| %>
						<li>
						<%= msg %>
						</li>
					<%end%>	
				</ul>
			</div>
		<% end %>
		<body>
		 	<table border="0" cellpadding="0" cellspacing="0" width="60%">
	      		<tr>
	        		<td width="120px">
						<%= f.label :name %>
					</td>
					<td width="120px">
	    				<%= f.text_field :name %>
	  				</td>
	 	 		</tr>
	 	 		<tr>
	 				<td align="center">
						<%= f.submit%>
					</td>
		 		</tr>
		 		<tr>
	 				<td align="center">
						<%= link_to 'Back', subjects_path%>
					</td>
				</tr>
			</table>
		</body>
	<% end %>
		

app/views/subjects/new.html.erb
<%= form_for :subject, url: subjects_path do |f| %>
	<% if @subject.errors.any? %>
		<div id="error explaination">
			<h2>
				<%= pluralize(@subject.errors.count,"error") %> Prohibited this subject from being saved:
			</h2>
			<ul>
				<% @subject.errors.full_messages.each do|msg|%>
				<li>
					<%= msg%>
				</li>
				<%end%>
			</ul>
		</div>
	<%end%>
	<div align="center" width="">
		<strong>Add New Subject</strong>
	</div>
	<body>
	 <table border="0" cellpadding="0" cellspacing="0" width="60%">
      <tr>
        <td width="120px">
			     <%= f.label :name %>
		    </td>
		    <td width="120px">
    		   <%= f.text_field :name %>
  		  </td>
 	    </tr>
 	    <tr>
 		   <td align="center">
			   <%= f.submit%>
		   </td>
	    </tr>
	    <tr>
 		   <td align="center">
			   <%= link_to 'Back', schools_path%>
		   </td>
	    </tr>
	 </table>
	</body>
 <% end -%>

app/views/subjects/show.html.erb
<div align="center" width="">
		<strong>View Subject Details</strong>
</div>
<table border="1">
	<tr>
		<td>
			<strong>Subject Name</strong>
		</td>
	</tr>
	<tr>
		<td>
			<%= @subject.name %>
		</td>
	</tr>
</table>
<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path%>