config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  get '/classrooms/filtered_index' => 'classrooms#filtered_index'
  get '/classrooms/filtered_index_classroom' => 'classrooms#filtered_index_classroom'
  get '/teachers/filtered_index' => 'teachers#filtered_index'
  get '/teachers/filtered_index_teacher' => 'teachers#filtered_index_teacher' 
  get '/students/filtered_index' => 'students#filtered_index'

  resources :schools , :classrooms, :teachers, :students, :subjects

  
  

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	belongs_to :school
	has_and_belongs_to_many :students
	has_and_belongs_to_many :classrooms
	has_and_belongs_to_many :subjects

	validates :name, :gender, :phone_no, presence: true
	validates :phone_no, uniqueness: true, length: {minimum:10, maximum:10}

	def school_details
		self.school
	end
	def classroom_details
		self.classrooms
	end
	def subject_details
		self.subjects
	end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
	def index
		@teachers=Teacher.all
		respond_to do |format|
 		format.json { render :json => @teacher, :status  => :ok }
 		end	
	end
	def show
		begin
			@teacher =Teacher.find(params[:id])
			respond_to do |format|
			format.json { render :json => @teacher, :status  => :ok }
			end
			rescue => e
			p e.message
			respond_to do |format|
 			format.json { render :json =>  { "error" => e.message}, :status  => :unprocessable_entity}
			end
		end
	end
	def create
		@teacher = Teacher.new(params.require(:teacher).permit(:name,  :gender, :phone_no, :school_id).merge(:classroom_ids=>params[:teacher][:classroom_ids],:subject_ids=>params[:teacher][:subject_ids]))
		if @teacher.save!
			respond_to do |format|
 			format.json { render :json => @teacher, :status  => :ok}
			end
		else
			respond_to do |format|
 			format.json {render :json => { "error"=> @teacher.errors}, :status  => :unprocessable_entity}
 			end
		end
	end
	def update
		begin
		@teacher=Teacher.find(params[:id])
		if @teacher.update_attributes!(params.require(:teacher).permit(:name,  :gender, :phone_no, :school_id).merge(:classroom_ids=>params[:teacher][:classroom_ids],:subject_ids=>params[:teacher][:subject_ids]))
			respond_to do |format|
 			format.json { render :json => @teacher, :status  => :ok}
			end
		else
			respond_to do |format|
 			format.json {render :json => { "error" => e.message}, :status  => :unprocessable_entity}
 			end
		end
			rescue => e
			p e.message
			respond_to do |format|
 			format.json {render :json => { "error" => e.message}, :status  => :unprocessable_entity}
 			end
		end
	end
	def destroy
		begin
		@teacher=Teacher.find(params[:id])
		if @teacher.destroy
			respond_to do |format|
 			format.json { render :json => @teacher, :status  => :ok}
			end
		end
		rescue => e
			p e.message
			respond_to do |format|
 			format.json {render :json => { "error" => e.message}, :status  => :unprocessable_entity}
 			end
		end
	end
	def filtered_index
    # refactor this to generate dynamic query
	  begin
	  	@school = School.find(params[:school_id])
	    @teachers = Teacher.where(:school_id => @school.id)
	 	  render :json => @teachers.to_json(:methods => [:teacher, :classroom_details, :subject_details, :school_details]), :status => :ok
		  rescue => e
		  p e.message
		  respond_to do |format|
	 	  format.json {render :json =>  { "error" => e.message}, :status  => :unprocessable_entity}
	 	  end
	  end
  end
  def filtered_index_teacher
    # refactor this to generate dynamic query
    begin
    	if params[:teacher_id] 
  		@teachers = Teacher.where(:id => params[:teacher_id]).all
 		  render :json => @teachers.to_json(:methods => [:teacher, :classroom_details, :subject_details, :school_details]), :status => :ok
			else
	    	format.json {render :json =>  "error", :status  => :unprocessable_entity}
	    end	
			rescue => e
			p e.message
			respond_to do |format|
 			format.json {render :json =>  { "error" => e.message}, :status  => :unprocessable_entity}
 		end
	  end
  end
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_for @teacher do |f| %>
 
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@teacher.errors.count, "error") %> prohibited
        this teacher from being saved:
      </h2>
      <ul>
        <% @teacher.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <p>
    <%= f.label :school_id %><br>
    <%= select_tag 'teacher[school_id]', options_from_collection_for_select(School.all, :id, :name) %>
 </p>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
   <%= f.label :gender %><br>
    <select name="teacher[gender]" id="teacher_gender">
        <option value="Male" selected>Male</option>
        <option value="Female">Female</option>
    </select>
  </p>
  <p>
    <%= f.label :phone_no%><br>
    <%= f.text_field :phone_no%>
  </p>
 
  
  
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/teachers/_teacher.html.erb
<div id="allTeacher" class="hidden" align="center">
   <h3>Teacher List</h3>
   <a class="btn btn-success" id="createTeacher">Add New Teacher</a></br>
   <input type="hidden" id="hiddenSchoolId"></br>
   <input type="hidden" id="hiddenSchoolName">
    <table border="1" id="tableTeacher" width="70%" class="table table-bordered">
     <thead>
      <tr>
        <th>
          School Name
        </th>
        <th>
          Classroom Name
        </th>
        <th>
           Teacher Name
        </th>
        <th>
           Gender
        </th>
        <th>
          Phone No
        </th>
        <th>
          Proficiency Subject
        </th>
         <th colspan="6">
          Actions
        </th> 
      </tr>
     </thead>
    <tbody>
    </tbody>
    </table>
    <button id="home" type="button" class="btn btn-warning">Home</button>
    <button id="back" type="button" class="btn btn-default">Back</button>
    <input type="hidden" id="hdnSchoolName">
    <input type="hidden" id="hiddenSchoolId">
</div>
<div id="createTeacherContainer" class="hidden" align="center">
  <form action=""  id="createTeacherForm" method="" class="form-horizontal">
    <div class="container">
      <div class="row" >
        <div class="col-md-3">
        </div>
        <div class="col-md-6">
          <div ><h3>Create Teacher</h3></div>

          <div class="form-group">
            <div class="col-sm-4">
              <label>School Name :</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="schoolName" disabled>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-4">
              <label>Classroom Name :</label>
            </div>
            <div class="col-sm-4">
              <select id="ddClassroom" width="10px" name="teacher_class">
              </select>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-4">
              <label>Teacher Name :</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="teacherName" name="teacher_name">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-4">
              <label>Gender :</label>
            </div>
            <div class="col-sm-4">
              <select id="gender" name="teacher_gender">
                <option value="Male" selected>Male</option>
                <option value="Female">Female</option>
              </select>
          </div>
          </div>
          <div class="form-group">
            <div class="col-sm-4">
              <label>Phone No :</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="phoneNo" name="teacher_phone">
            </div>
          </div>
          <div class="form-group"> 
            <div class="col-sm-4">
              <label>Subject :</label>
            </div>
            <div class="col-sm-4">
               <select id="ddSubject" multiple="true" size="3" width="10px" name="teacher_subject">
               </select>
               <input type="hidden" id="schoolHidden">
               <input type="hidden" id="schoolIdHidden">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-4">
              <button type="button" id="btnCreateTeacher" class="btn btn-primary" >Submit</button>
            </div>
            <div class="col-sm-4">
             <button type="button" id="cancel" class="btn btn-warning">Cancel</button>
            </div>
          </div>
        </div>
        <div class="col-md-3">
        </div>
        </div>
     </div>
     </div>
  </form>
</div>
<div id="editTeacherContainer" class="hidden" align="center">
 <form action=""  id="editTeacherForm" method="" class="form-horizontal">
    <div class="container">
      <div class="row" >
        <div class="col-md-3">
        </div>
        <div class="col-md-6">
          <div ><h3>Edit Teacher</h3>
          </div>
          <div class="form-group">
            <div class="col-sm-4">
              <label>School Name :</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="schoolName" disabled>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-4">
              <label>Classroom Name :</label>
            </div>
            <div class="col-sm-4">
              <select id="ddClassroom"  width="10px" name="teacher_class" disabled>
              </select>
          </div>
          </div>
          <div class="form-group">
            <div class="col-sm-4">
              <label>Teacher Name :</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="teacherName" name="teacher_name">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-4">
              <label>Gender :</label>
            </div>
            <div class="col-sm-4">
              <select id="gender" name="teacher_gender">
                <option value="Male" selected>Male</option>
                <option value="Female">Female</option>
              </select>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-4">
              <label>Phone No :</label>
            </div>
            <div class="col-sm-4">
              <input type="text" id="phoneNo" name="teacher_phone">
            </div>
          </div>
          <div class="form-group"> 
            <div class="col-sm-4">
              <label>Subject :</label>
            </div>
            <div class="col-sm-4">
              <select id="ddSubject" multiple="true" size="3" width="10px" name="teacher_subject">
              </select>
              <input type="hidden" id="schoolHidden">
              <input type="hidden" id="schoolIdHidden">
            </div>
          </div>
          <div class="form-group"> 
            <div class="col-sm-4">
              <button type="button" id="btnEditTeacher" class="btn btn-primary">Update</button>
            </div>
            <div class="col-sm-4">
             <button type="button" id="cancel" class="btn btn-warning">Cancel</button>
            </div>
          </div>
        </div>
        <div class="col-md-3">
        </div>
        </div>
     </div>
     </div>
  </form>
</div>

app/views/teachers/edit.html.erb
<h3>Edit Teacher Details</h1>

	<%= form_for :teacher, url: teacher_path(@teacher.id) , method: :patch do |f| %>
	
		<%if @teacher.errors.any?  %>
			<div id="error_explain">
				<h2>
					<%= pluralize(@teacher.errors.count, "error")%> Prohibited this teacher from being edited
				</h2>
				<ul>
					<%= @teacher.errors.full_message.each do |msg| %>
						<li>
							<%= msg %>
						</li>
					<%end%>	
				</ul>
			</div>
		<% end %>

		<body>
		 <table border="0" cellpadding="0" cellspacing="0" width="60%">
			<tr>
	          <td>
	            <%= f.label :school_id %><br>
	          </td>
	          <td>
	             <%= @teacher.school.name%>
	          </td>
	      	</tr>
	      	<tr>
            <td>
              <%= f.label :classroom_id%>
            </td>
            <td>
              <%= select_tag 'teacher[classroom_ids]', options_from_collection_for_select(Classroom.all, :id, :name,:selected=>@teacher.classrooms.collect(&:id)), 
              { :multiple => true }%>
             
            </td>
          </tr>
	      	<tr>
	          <td width="120px">
	  			     <%= f.label :name %>
	  		  </td>
	  		  <td width="120px">
	      		  <%= f.text_field :name %>
	    		</td>
	 	    </tr>
	   	 	<tr>
	      		<td width="120px">
	      		<%= f.label :gender %>
	      		</td>
	      		<td width="120px">
	      		<%= f.select :gender, ['Male', 'Female']%>
	      			
	      		</td>
	    	</tr>
	 		<tr>
	 			<td width="120px">
	 				 <%= f.label :phone_no%>
	 			</td>
	 			<td>
	 				<%= f.number_field :phone_no %>
	 			</td>
	 		</tr>
	 		<tr>
	 			<td>
	 				 <%= f.label :subject_id%>
	 			</td>
	 			<td>
	 				 <%= select_tag 'teacher[subject_ids]', options_from_collection_for_select(Subject.all, :id, :name,:selected=>@teacher.subjects.collect(&:id)), { :multiple => true }%>
	 			</td>
	 		</tr>
		 	<tr>
		 		<td align="center">
					<%= f.submit%>
				</td>
			</tr>
			<tr>
		 		<td align="center">
					<%= link_to 'Back', teachers_path%>
				</td>
			</tr>
		</body>
<% end %>
		

app/views/teachers/index.html.erb
<h3>Listing Teachers</h1>
<%= link_to 'Add New Teacher', new_teacher_path %></h3></br></br>
<table border="1">
	<tr>
		<th>
			Teacher Name
		</th>
		<th>
			 Gender
		</th>
		<th>
			Phone Number
		</th>
		<th>
			Proficiency Subject
		</th>
		<th>	
			School
		</th>
		<th>	
			Classroom
		</th>
		
		<th colspan="6">
			Actions
		</th>
	</tr>
	<% @teachers.each do |teacher|%>
		<tr>
			<td>
				<%= teacher.name%>
			</td>
			<td>
				<%= teacher.gender%>
			</td>
			<td>
				<%= teacher.phone_no%>
			</td>
			<td>
				<%= teacher.subjects.collect(&:name).join(",")%>
			</td>
			<td>
				<%= teacher.school.name%>
			</td>
			<td>
			
				<%= teacher.classrooms.collect(&:name).join(",")%>
			</td>
			<td colspan="2">
				<%= link_to 'Show', teacher_path(teacher) %>
			</td>
			<td colspan="2">
				<%= link_to 'Edit', edit_teacher_path(teacher) %>
			</td>
			<td colspan="2">
				<%= link_to 'Destroy', teacher_path(teacher), method: :delete, data: { confirm: 'Do you want to destroy this record?' } %>
			</td>
		</tr>

	<%end%>

</table>
<%= link_to 'Back', schools_path %></br></br>

app/views/teachers/new.html.erb
<!-- <h1>New Classroom</h1> -->
<%= form_for :teacher, url: teachers_path do |f| %>
	<% if @teacher.errors.any? %>
		<div id="error explaination">
			<h2>
				<%= pluralize(@teacher.errors.count,"error") %> Prohibited this teacher from being saved:
			</h2>
			<ul>
				<% @teacher.errors.full_messages.each do|msg|%>
				<li>
					<%= msg%>
				</li>
				<%end%>
			</ul>
		</div>
	<%end%>
	<div align="center" width="40%">
		<strong>Add New Teacher</strong>
	</div>
	<body>
	 <table border="0" cellpadding="0" cellspacing="0" width="60%">
          <tr>
            <td>
              <%= f.label :school_id %>
            </td>
            <td>
               <%= select_tag 'teacher[school_id]', options_from_collection_for_select(School.all, :id, :name) %>
            </td>
          </tr>
          <tr>
            <td>
              <%= f.label :classroom_id%>
            </td>
            <td>
              <%= select_tag 'teacher[classroom_ids]', options_from_collection_for_select(Classroom.all, :id, :name), 
              { :multiple => true, :size =>3 } %>
            </td>
          </tr>
          <tr>
            <td width="120px">
               <%= f.label :name %>
          </td>
          <td width="120px">
              <%= f.text_field :name %>
          </td>
        </tr>
        <tr>
            <td width="120px">
              <%= f.label :gender %>
            </td>
            <td width="120px">
              <select name="teacher[gender]" id="teacher_gender">
                <option value="Male" selected>Male</option>
                <option value="Female">Female</option>
             </select>
            
            </td>
        </tr>
      <tr>
        <td width="120px">
           <%= f.label :phone_no%>
        </td>
        <td>
          <%= f.text_field :phone_no ,:maxlength => 10,:size => 20 %>
        </td>
      </tr>
      <tr>
        <td>
           <%= f.label :proficiency_subject%>
        </td>
        <td>
         <%= select_tag 'teacher[subject_ids]', options_from_collection_for_select(Subject.all, :id, :name), 
              { :multiple => true, :size =>3 } %>
        </td>
      </tr>
    	
   	<tr>
   		<td align="center">
  			<%= f.submit%>
  		</td>
  	</tr>
  	<tr >
   		<td align="center">
  			<%= link_to 'Back', teachers_path%>
  		</td>
  	</tr>
	</body>
 <% end -%>

app/views/teachers/show.html.erb
<div align="center" width="">
		<strong>View Teacher Details</strong>
</div>
<table border="1">
	<tr >
		<td>
			<strong>Teacher Name</strong>
		</td>
		<td>
			<strong>Gender</strong>
		</td>
		<td>
			<strong>Phone No</strong>
		</td>
		<td>
			<strong>Proficiency Subject</strong>
		</td>
		<td align="center">
			<strong>School</strong>
		</td>
		<td align="center">
				<strong>Classroom</strong>
		</td>
	</tr>
	<tr>
		<td>
			<%= @teacher.name %>
		</td>
		<td>
			<%= @teacher.gender %>
		</td>
		<td>
			<%= @teacher.phone_no%>
		</td>
		<td>
			<%= @teacher.subjects.collect(&:name).join(",")%>
		</td>
		<td>
			<%= @teacher.school.name%>
		</td>
		<td>
			<%= @teacher.classrooms.collect(&:name).join(",")%>
		</td>
	</tr>

</table>
<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path%>